// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
	    int N = Integer.parseInt(args[0]);

        int Over = 0;
        int UnderEqual = 0;

        for (int i = 0; i < N; i++) 
		{
            double ran = Math.random();
            if (ran > 0.5) 
			{
                Over++;
            } 
			else 
			{
            	UnderEqual++;
            }
        }

        System.out.println("> 0.5: " + Over + " times");
        System.out.println("<= 0.5: " + UnderEqual + " times");

        if (UnderEqual != 0) 
		{
            double ratio = (double) Over / UnderEqual;
            System.out.println("Ratio: " + ratio);
        }
    }
}
	

